### ISSUE TITLE
Move avatar url and info retrieve from avatar.js to people.js

### ISSUE THREAD

**Issue by jwendell** [jwendell/gnome-shell-extension-timezone#12]
Avatar class is getting messy... ideally it should receive all data it needs to draw the avatar, no need to retrieve that info itself...

Also, People class must have this info beforehand in order to calculate some info, like the name of top city.

**Comment by jjgonzalez-tiempodev** [comment]
I realized this as well while coding github support.
I agree Person, acting like json parser whould provide all this information and pass it to avatar and others. Like this approach.
