### ISSUE TITLE
Icon wrap around

### ISSUE THREAD

**Issue by laramy2020** [jwendell/gnome-shell-extension-timezone#17]
i have a 24 inch 1080p monitor and i have a lot of people in 1 time zone (14 only 12 show) and it goes off the bottom edge of the screen

Add a hight limit to the window and a new collum after X about of people.
or add a multi-city colum under each TimeZone if cities are defined (still apply the above if the list contains a lot of people in the same city as mine dose)

**Comment by jwendell** [comment]
Hi. Although I don't have such big monitor, I've tried my best to fix this bug. Could you please verify if it's fixed for you? If not, please reopen this issue telling what is wrong. Thanks.

**Comment by laramy2020** [comment]
Yep That fixed it!

**Comment by jwendell** [comment]
actually it's a clock :D
I'm curious, what was it before?

**Comment by laramy2020** [comment]
it was a clock before. the latest git pull is a puzzle piece

**Comment by jwendell** [comment]
so, could you please take a screenshot and fill a new issue?

**Comment by laramy2020** [comment]
Will Do.
