### ISSUE TITLE
Clock icon missing in latest git pull

### ISSUE THREAD

**Issue by laramy2020** [jwendell/gnome-shell-extension-timezone#20]
The icon was replaced with some generic puzzle piece.
![timezone](https://cloud.githubusercontent.com/assets/1227781/14829867/b80cb66c-0bbb-11e6-8228-337d50e56971.png)
enjoy my horrid gimp work!

**Comment by jwendell** [comment]
Which theme are you using? Is it a custom one? Can I easily use it here too?

**Comment by laramy2020** [comment]
oh it is my icon theme. strange, it was working with the paper icon theme before. wonder what happened. Switching back to default icon theme fixed it for now. but yes the theme is the Paper icon theme.

**Comment by laramy2020** [comment]
Awesome you are quick. icon stays on icon set change.
