### ISSUE TITLE
instant logout when enabeling

### ISSUE THREAD

**Issue by mray** [jwendell/gnome-shell-extension-timezone#23]
After having updated some *other* extensions timezone instantly logs me out of my current session.
This is as bad as a system crash to me.

**Comment by jwendell** [comment]
Hi!

Could you please send a log of the current session when this occurs?
Something like running "journalctl -f /usr/bin/gnome-shell" in a terminal and then trying to reproduce the problem. Copy and paste the log here.

Also, what's the complete list of enabled extensions you have? So I can install them and try to reproduce the issue here.

Thanks!

**Comment by mray** [comment]
I'm running the version from extensions.gnome.org.
I can't send a log since I instantly log out and go to hibernate after I turn it on.
Here are the other extensions I use:
![untitled](https://cloud.githubusercontent.com/assets/164785/18248735/6b94cbae-737a-11e6-93d8-6a3553778a1e.png)

**Comment by jwendell** [comment]
Regarding the log, you could, for instance:
1) Open a terminal (shell console), and run the command
`journalctl -f /usr/bin/gnome-shell > ~/shell-log`

2) Enable the extension
3) Once you have access again to your system, open the file '~/shell-log' and paste the content here.

But, before that, you could try run the extension from git, as stated in https://github.com/jwendell/gnome-shell-extension-timezone#other-way. There are a few commits [yet unreleased on extensions.gnome.org] that might have already a fix for this.

**Comment by mray** [comment]
The github version seems to work fine.
I removed the extension from  extensions.gnome.org and after entering this:
```
$ mkdir -p ~/.local/share/gnome-shell/extensions
$ git clone https://github.com/jwendell/gnome-shell-extension-timezone.git ~/.local/share/gnome-shell/extensions/timezone@jwendell
$ gnome-shell-extension-tool -e timezone@jwendell
```
I can use the extention again without any issue.

**Comment by jwendell** [comment]
Thanks, I'll release a new version for extensions.gnome.org with those fixes from master.
