### ISSUE TITLE
indicator content is duplicated when modifying people.json

### ISSUE THREAD

**Issue by hferreiro** [jwendell/gnome-shell-extension-timezone#30]
If the people.json file is modified, the timezone indicator displays its data twice.

**Comment by jwendell** [comment]
Which version of the extension are you using?
```sh
grep '"version"' ~/.local/share/gnome-shell/extensions/timezone@jwendell/metadata.json
```

I'm using latest one (v7) and couldn't reproduce the issue. Could you give more details? Which part of people.json that's changed triggers the issue? Any of it?

**Comment by ibahnasy** [comment]
I can confirm this issue, I'm running vesrion 7 as well.

It happens only on fresh startup of the gnome-shell, the defined timzones in people.json file are duplicated in the extension menu; if you relogin you can reproduce too.
When I refresh the Shell by executing 'r' in the Alt+F2 command, it extension display the defined zones correctly without duplication.

**Comment by ibahnasy** [comment]
BTW, this happens only when using Xorg but in Wayland it works fine just after login.

**Comment by stav** [comment]
I can confirm this in Wayland as well. I changed the city for one person in the JSON file and now everything is duplicated.

	$ grep '"version"' ~/.local/share/gnome-shell/extensions/timezone@jwendell/metadata.json
	"version": 7

**Comment by dimgrav** [comment]
Came here to open this issue, it only happens on boot/log-in. A gnome-shell restart causes the contents to be displayed properly.

**Comment by str** [comment]
Same error in version 9

**Comment by thiagodasilva** [comment]
Same error, the workaround is to change one of the settings and save.

**Comment by jwendell** [comment]
Today I faced this issue, and managed to reproduce it. I pushed a fix for it, a new version is already uploaded into extensions.gnome.org, I'm just waiting for it to to be approved. I appreciate if you guys could test it and confirm the issue is gone. Thank you for your patience :)
