### ISSUE TITLE
Alternative locations for people.json file

### ISSUE THREAD

**Issue by jwendell** [jwendell/gnome-shell-extension-timezone#4]
Like another directory or even a URL for a remote location

**Comment by aldomann** [comment]
Agreed. The directory should be `~/.local/share/gnome-shell/extensions/timezone@jwendell`.

**Comment by aldomann** [comment]
@jwendell just found that setting line 14 in `people.js` to `this._path = GLib.build_filenamev([GLib.get_home_dir(), '.local/share/gnome-shell/extensions/timezone@jwendell/people.json']);` works as a charm.

**Comment by jwendell** [comment]
I'm sure it works... I'm wondering more at a generic approach, with the main goal of supporting a remote file. AKA: How do we allow the user to supply a remote url for this file.

I think we need to provide an UI for that... :(
