### ISSUE TITLE
Doesn't work on Ubuntu 19.04.

### ISSUE THREAD

**Issue by milosb793** [jwendell/gnome-shell-extension-timezone#40]
Hi all, 

it seems like the extension isn't working on Ubuntu 19.04. with GNOME 3.32.2, but it had worked perfectly on 18.04.3 before I did upgrade. 

![Screenshot-2019-09-17-11-25-06](https://user-images.githubusercontent.com/5012355/65029389-f2b9b500-d93d-11e9-83c9-8147d4ae67f9.png)

**Comment by milosb793** [comment]
Just to mention, tried to reinstall, via web as well as via cli, and still not working.

**Comment by jwendell** [comment]
Hi! I just installed an ubuntu vm and installed the extension, it worked fine: https://pasteboard.co/IxOVN2R.png

Could you please provide logs? Like:
- in a terminal, run journalctl -f /usr/bin/gnome-shell
- in other terminal, disable and enable the extension
- copy and paste output from logs

**Comment by milosb793** [comment]
Hey @jwendell , thanks for super-fast response! It seems it was something temporary, it got fixed by itself, I did nothing.
