### ISSUE TITLE
"error in people.json" on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by hdrodel** [jwendell/gnome-shell-extension-timezone#41]
I installed this extension like discribed in [the github page.](https://github.com/jwendell/gnome-shell-extension-timezone) 
i added a people.json file like in the manual but whenever i opened the extension it only showed that there was an error parsing my people.json file. `journalctl -f /usr/bin/gnome-shell` showed this error: `Error parsing file:///home/hdrodel/people.json: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data`

I looked at the file `people.js` if i change line 79 from 
`rawPeople = JSON.parse(ByteArray.toString(contents));` 
to this:
 `rawPeople = JSON.parse(contents);`
the extension starts working as expected 

Is this a problem with the extension or my setup?

**Comment by klyuko** [comment]
> I installed this extension like discribed in [the github page.](https://github.com/jwendell/gnome-shell-extension-timezone)
> i added a people.json file like in the manual but whenever i opened the extension it only showed that there was an error parsing my people.json file. `journalctl -f /usr/bin/gnome-shell` showed this error: `Error parsing file:///home/hdrodel/people.json: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data`
> 
> I looked at the file `people.js` if i change line 79 from
> `rawPeople = JSON.parse(ByteArray.toString(contents));`
> to this:
> `rawPeople = JSON.parse(contents);`
> the extension starts working as expected
> 
> Is this a problem with the extension or my setup?

Thank you! You helped me

**Comment by boyod** [comment]
Problem with reading a timezone file (people.json)! The syntax file from the readme.md file also does not work!

**Comment by boyod** [comment]
Manual installation did not complete completely, the schema file did not download, and nothing worked. Reinstallation through the application manager - helped).

**Comment by Voronenko** [comment]
I do confirm presence of the issue with 

```js
rawPeople = JSON.parse(ByteArray.toString(contents));
```
in people.js which starts working when replaced with `rawPeople = JSON.parse(contents);`

**Comment by jwendell** [comment]
Thanks for the suggestions, folks. I've applied it on the source and pushed the fix. A new version with this fix should reach out extensions.gnome.org soon.
