### ISSUE TITLE
[ Add request ] Change the clock logo by a specific time

### ISSUE THREAD

**Issue by 72y9op** [jwendell/gnome-shell-extension-timezone#43]
Hello, I would like to know if you can add an option to be able to change the "clock" logo by one hour from one of the partners, thank you!

**Comment by jwendell** [comment]
Hi! I'm not sure I understand your request, could you please clarify it a bit more?

**Comment by 72y9op** [comment]
Yes excuse me, currently we have a clock-shaped logo in the top bar, I would like to know if it is possible that instead of this logo we can set the time of one of the teammates, ex: I work with a friend at japan, suddenly at the top i would see its current time. You understand suddenly, if this is still not the case I can show you an example

**Comment by jwendell** [comment]
Gotcha! I think this feature does not fir well in this extension.

Doing a quick search by `clock` on https://extensions.gnome.org I found some extensions that does what you want, like https://extensions.gnome.org/extension/2657/timezones-extension/ or https://extensions.gnome.org/extension/1479/top-bar-clocks/

**Comment by 72y9op** [comment]
Yes yes thank you it’s that
