### ISSUE TITLE
error in 20.04 "global.screen is undefined"

### ISSUE THREAD

**Issue by ericmigi** [jwendell/gnome-shell-extension-timezone#45]
![image](https://user-images.githubusercontent.com/1048265/80289414-24280980-86f3-11ea-85ec-da3320f7c81a.png)

**Comment by jwendell** [comment]
Hi, please, check the version of the extension, you are probably using an old version. We do not use `global.screen` anymore. See https://github.com/jwendell/gnome-shell-extension-timezone/issues/32
