### ISSUE TITLE
TypeError: theme is null

### ISSUE THREAD

**Issue by jalberto** [jwendell/gnome-shell-extension-timezone#47]
The first time the extension initializes correctly but after restart/session it throw this error:

TypeError: theme is null

**Comment by jwendell** [comment]
Thanks. Hopefully this is fixed in master. A new version should reach out extensions.gnome.org soon.

**Comment by jwendell** [comment]
For reference, this is the issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1997
