### ISSUE TITLE
Does not work on Gnome 3.38.1 - meta is null error

### ISSUE THREAD

**Issue by str** [jwendell/gnome-shell-extension-timezone#49]
Creat project, congrats. It's one of my critical apps.

It stopped working after the ubuntu 20.10 upgrade :(

**Comment by jwendell** [comment]
Thanks, I just got hit by this issue, after upgrading. Hopefully I'll fix it soon.

**Comment by jwendell** [comment]
This is fixed in master. A new version should reach https://extensions.gnome.org/extension/1060/timezone/ soon.

**Comment by str** [comment]
Confirmed today. Thank you.
