### ISSUE TITLE
Create an GUI editor for people.json file?

### ISSUE THREAD

**Issue by jwendell** [jwendell/gnome-shell-extension-timezone#5]

**Comment by laramy2020** [comment]
I might give this a shot this weekend. it will be incredably basic, are you ok with that?

**Comment by jwendell** [comment]
I'm not sure yet if this is a thing we want to have. Show me your work, if I like it, why not?

**Comment by laramy2020** [comment]
https://github.com/laramy2020/gnome-shell-extension-timezone-gui
Go ahead and take a quick look. i am finishing up the readme.md
