### ISSUE TITLE
Not working in GNOME 40

### ISSUE THREAD

**Issue by philn** [jwendell/gnome-shell-extension-timezone#52]
```
TypeError: this.add is not a function

Stack trace:
  _init@/var/home/phil/.local/share/gnome-shell/extensions/timezone@jwendell/prefs.js:21:14
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/var/home/phil/.local/share/gnome-shell/extensions/timezone@jwendell/prefs.js:134:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by gpoo** [comment]
For the record, this time there is a [guide to port extensions to gnome shell 40](https://gjs.guide/extensions/upgrading/gnome-shell-40.html).

**Comment by ahopkins** [comment]
Is there planned upgrade?

**Comment by jwendell** [comment]
I can only work on this when I upgrade to GNOME 40. Patches are welcome (although I won't be able to test them myself)

**Comment by ahopkins** [comment]
FWIW, this extension was the reason I was planning to wait for Gnome 40.

**Comment by ahopkins** [comment]
So, It was only a matter of adding `"40"` to the `shell-version` in `metadata.json` and it works :tada:

**Comment by philn** [comment]
Is the settings UI also working without any modification?

**Comment by ahopkins** [comment]
I am not sure which UI you are talking about. I have only ever managed the extension through the JSON file.

**Comment by jwendell** [comment]
> I am not sure which UI you are talking about. I have only ever managed the extension through the JSON file.

@ahopkins , In the extension popup, there is a label in the bottom saying: `X people in Y timezones...`. This is actually a button. Clicking on it opens the settings @philn mentioned.

**Comment by ahopkins** [comment]
TIL

**Comment by ahopkins** [comment]
```
TypeError: this.add is not a function

Stack trace:
  _init@/home/adam/.local/share/gnome-shell/extensions/timezone@jwendell/prefs.js:21:14
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/home/adam/.local/share/gnome-shell/extensions/timezone@jwendell/prefs.js:134:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

![image](https://user-images.githubusercontent.com/166269/115125100-b1343480-9fce-11eb-81d8-ddae4c312d92.png)

**Comment by jwendell** [comment]
Finally got some time to upgrade to GNOME 40. Pushed a fix that should close this issue. A new revision is waiting for review at https://extensions.gnome.org/extension/1060/timezone/ . Once it's approved, it should update automatically.
