### ISSUE TITLE
Gnome 42

### ISSUE THREAD

**Issue by Queatz** [jwendell/gnome-shell-extension-timezone#58]
After updating to Ubuntu 22.04 with Gnome 42, I get this error:

"Object 0xe5a936288c8 is not a subclass of GObject_Object, it's a Object"

**Comment by weizhouapache** [comment]
I upgraded to ubuntu 22.04 and faced same issue.

I expect someone to fix it.

**Comment by ahopkins** [comment]
What an unpleasant surprise to wake up one morning to find this missing. :cry: 

Hoping the resolution is quick.

**Comment by jwendell** [comment]
I have fixed this issue. It should show up on https://extensions.gnome.org/extension/1060/timezone/ and be available as an update soon.

**Comment by weizhouapache** [comment]
great, thanks @jwendell for fixing. it works fine !

**Comment by spencerflagg** [comment]
Fantastic! The fix works great.
Perfect timing for me - I just got a new out-of-timezone client and was preparing to sorely miss this plugin.
