### ISSUE TITLE
file picker doesn't work

### ISSUE THREAD

**Issue by thob** [jwendell/gnome-shell-extension-timezone#59]
hey, I'm on Pop_OS 22.04. For some reason the file picker for the json file stopped working. I'm not able to use http either.
Any ideas how to cure this?

I'm using extension sync and I believe this interferes somehow as it show the PATH from my other box

Update: where is the path that shows actually coming from, I could overwrite it?

Any idea?

Thanks

**Comment by mrenvoize** [comment]
I'm also having this issue

**Comment by mariospr** [comment]
Yes, this issue is still there, the only way to get this working seems to be to have the people.json file in your home directory.

**Comment by mariospr** [comment]
The problem was a simple missing migration `this.get_root() -> this.box.get_root()` in `prefs4.js`.

Please take a look to the PR https://github.com/jwendell/gnome-shell-extension-timezone/pull/61

Thanks!

**Comment by thob** [comment]
this only works 50% now, It reads the from some old version of the .json. Changes are not reflected, also I can't got for a https:// file
