### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by str** [jwendell/gnome-shell-extension-timezone#60]
After updating to Ubuntu 22.10 with Gnome 43, the clock is still showing, but not reading the timezones file, nor showing anything

![image](https://user-images.githubusercontent.com/123817/199535513-5635ce21-5036-4710-bfa9-6768b4ce0053.png)

**Comment by mrenvoize** [comment]
Hmm, I don't even get a clock with my Gnome 43... The Icon and an Empty widget on click.

**Comment by paoloantinori** [comment]
Just wanted to confirm this works on Fedora 37. Thank you very much!

**Comment by str** [comment]
Confirmed to work on Ubuntu 22.10 too. Thank you very much.
